### ISSUE TITLE
Easier Pre-HV Gunpower creation

### ISSUE THREAD

**Issue by Muramasa-** [Muramasa-/TakPak#33]
Add Saltpeter Ore to an ore mix in the nether so gunpower can be mass-produced before having access to the Pyrolyse oven.

**Comment by devonushka** [comment]
Specifically, it's too resource and power intensive to make the first rocket to go to the moon. The problem with using gunpowder here is that gunpowder makes powder barrels, and power barrels are only 1/4 of one piece of TNT, so even with this solution you'd need a huge amount of gunpowder.
